export const LOGIN_SUCCESS = "LOGIN_SUCCESS";
export const LOGIN_FAIL = "LOGIN_FAIL";
export const LOGIN_REQUEST = "LOGIN_REQUEST";
export const LOG_OUT = "LOG_OUT";
export const LOAD_PROFILE = "LOAD_PROFILE";

export const HOME_VIDEO_SUCCESS = "HOME_VIDEO_SUCCESS";
export const HOME_VIDEO_FAIL = "HOME_VIDEO_FAIL";
export const HOME_VIDEO_REQUEST = "HOME_VIDEO_REQUEST";
export const SELECTED_VIDEO_REQUEST = "SELECTED_VIDEO_REQUEST";
export const SELECTED_VIDEO_SUCCESS = "SELECTED_VIDEO_SUCCESS";
export const SELECTED_VIDEO_FAILED = "SELECTED_VIDEO_FAILED";

export const CHANNEL_DETAIL_REQUEST = "CHANNEL_DETAIL_REQUEST";
export const CHANNEL_DETAIL_SUCCESS = "CHANNEL_DETAIL_SUCCESS";
export const CHANNEL_DETAIL_FAILED = "CHANNEL_DETAIL_FAIL";

export const SET_SUBSCRIPTION_STATUS = "SET_SUBSCRIPTION_STATUS";

export const COMMENT_LIST_REQUEST = "COMMENT_LIST_REQUEST";
export const COMMENT_LIST_SUCCESS = "COMMENT_LIST_SUCCESS";
export const COMMENT_LIST_FAILED = "COMMENT_LIST_FAILED";

export const ADD_COMMENT_SUCCESS = "ADD_COMMENT_SUCCESS";
export const ADD_COMMENT_FAILED = "ADD_COMMENT_FAILED";

export const RELATED_VIDEO_REQUEST = "RELATED_VIDEO_REQUEST";
export const RELATED_VIDEO_SUCCESS = "RELATED_VIDEO_SUCCESS";
export const RELATED_VIDEO_FAILED = "RELATED_VIDEO_FAILED";

export const SEARCH_VIDEO_REQUEST = "SEARCH_VIDEO_REQUEST";
export const SEARCH_VIDEO_SUCCESS = "SEARCH_VIDEO_SUCCESS";
export const SEARCH_VIDEO_FAILED = "SEARCH_VIDEO_FAILED";

export const SUBSCRIPTION_CHANNEL_REQUEST = "SUBSCRIPTION_CHANNEL_REQUEST";
export const SUBSCRIPTION_CHANNEL_SUCCESS = "SUBSCRIPTION_CHANNEL_SUCCESS";
export const SUBSCRIPTION_CHANNEL_FAILED = "SUBSCRIPTION_CHANNEL_FAILED";

export const CHANNEL_VIDEO_REQUEST = "CHANNEL_VIDEO_REQUEST";
export const CHANNEL_VIDEO_SUCCESS = "CHANNEL_VIDEO_SUCCESS";
export const CHANNEL_VIDEO_FAILED = "CHANNEL_VIDEO_FAILED";
